### ISSUE TITLE
Compilation error with Ubuntu 16.04

### ISSUE THREAD

**Issue by christiankakesa** [peme0815/dimecoin#3]
I have the error bellow when trying to compile with Ubuntu 16.04.
Any idea about this issue ?

```bash
/usr/include/boost/variant/get.hpp: In instantiation of 'typename boost::add_reference<T>::type boost::strict_get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]':
/usr/include/boost/variant/get.hpp:284:25:   required from 'typename boost::add_reference<T>::type boost::get(boost::variant<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19>&) [with U = const CScriptID&; T0 = CNoDestination; T1 = CKeyID; T2 = CScriptID; T3 = boost::detail::variant::void_; T4 = boost::detail::variant::void_; T5 = boost::detail::variant::void_; T6 = boost::detail::variant::void_; T7 = boost::detail::variant::void_; T8 = boost::detail::variant::void_; T9 = boost::detail::variant::void_; T10 = boost::detail::variant::void_; T11 = boost::detail::variant::void_; T12 = boost::detail::variant::void_; T13 = boost::detail::variant::void_; T14 = boost::detail::variant::void_; T15 = boost::detail::variant::void_; T16 = boost::detail::variant::void_; T17 = boost::detail::variant::void_; T18 = boost::detail::variant::void_; T19 = boost::detail::variant::void_; typename boost::add_reference<T>::type = const CScriptID&]'
src/rpcrawtransaction.cpp:245:77:   required from here
/usr/include/boost/variant/get.hpp:178:5: error: invalid application of 'sizeof' to incomplete type 'boost::STATIC_ASSERTION_FAILURE<false>'
     BOOST_STATIC_ASSERT_MSG(
     ^
Makefile:2219: recipe for target 'build/rpcrawtransaction.o' failed
make: *** [build/rpcrawtransaction.o] Error 1
```

I'm using this commands:

```bash
apt install -y -qq cmake build-essential qt4-default libssl-dev libboost-all-dev libdb++-dev libminiupnpc-dev
git clone https://github.com/peme0815/dimecoin.git
chmod +x dimecoin/src/leveldb/build_detect_platform
cd dimecoin
qmake RELEASE=1 USE_UPNP=1
make
```

**Comment by cryptohombre** [comment]
Did you ever figure this one out? I'm running into the exact same thing with Ubuntu 16.04

**Comment by cryptohombre** [comment]
Actually, I think I got it. I'm on Ubuntu 16.04 with boost 1.5.8

In order to get it to work, I needed to make the following code change:
in rpcrawtransaction.cpp, navigate to line 245 and change
`const CScriptID& hash = boost::get<const CScriptID&>(address);`
To this:
`const CScriptID& hash = boost::get<CScriptID>(address);`

After that, it compiled for me. Good luck!
